account.msg =Welcome to the Sophann Bank Accounts Default application git
account.build-version=3

account.mailDetails.hostName=default-accounts@piseth.com
account.maildetails.port=9000
account.mailDetails.from=default-accounts@piseth.com
account.mailDetails.subject=Your Account Details from Piseth Bank Default Environment

account.activeBranches[0]=Phnom Penh
account.activeBranches[1]=Kompong Cham
account.activeBranches[2]=Battombong