account.msg=Welcome to the Sophann Bank Accounts Dev application
account.build-version=2

account.mailDetails.hostName=dev-accounts@piseth.com
account.maildetails.port=9001
account.mailDetails.from=dev-accounts@piseth.com
account.mailDetails.subject=Your Account Details from Piseth Bank Dev Environment

account.activeBranches[0]=Kandal
account.activeBranches[1]=Banteay Meanchey
account.activeBranches[2]=Siem Reap